export default {
  // --------------UI METHODS --------------/
  TOGGLE_ITEM: 'TOGGLE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_VALUE: 'UPDATE_VALUE',
  // --------------API METHODS --------------/
              // ---- Get ----- //
  FETCH_ITEMS_REQUEST: 'FETCH_ITEMS_REQUEST',
  FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
              // ---- Del ----- //
  DELETE_ITEMS_REQUEST: 'DELETE_ITEMS_REQUEST',
  DELETE_ITEMS_FAILURE: 'DELETE_ITEMS_FAILURE',
  DELETE_ITEMS_SUCCESS: 'DELETE_ITEMS_SUCCESS',
              // ---- Post ----- //
  POST_ITEMS_REQUEST: 'POST_ITEMS_REQUEST',
  POST_ITEMS_FAILURE: 'POST_ITEMS_FAILURE',
  POST_ITEMS_SUCCESS: 'POST_ITEMS_SUCCESS',
              // ---- Update ----- //
  UPDATE_ITEMS_REQUEST: 'UPDATE_ITEMS_REQUEST',
  UPDATE_ITEMS_FAILURE: 'UPDATE_ITEMS_FAILURE',
  UPDATE_ITEMS_SUCCESS: 'UPDATE_ITEMS_SUCCESS'
}
